### ISSUE TITLE
Orin NX PWM minimum freq?

### ISSUE THREAD

**Issue by democat3457** [Rubberazer/JETGPIO#22]
I'm running this on an Orin NX and I'm confused as to why the minimum PWM frequency is 400 Hz. As far as I'm aware, this locks me out of most servo and motor control (since those are usually 50-100Hz). Would it be possible to go around whatever limitation this is to enable said servo and motor control? Thanks!

**Comment by Rubberazer** [comment]
Hi there

You are right, all those small servos don't tolerate going beyond 100Hz. 

I was aware that the minimum frequency running on the Orin pwms was a bit high, but at the time didn't give much importance to it, tested it, made sure it was working and moved on.

I updated the Orin source to take on frequencies from 50 to 1.59 GHz. it goes really nicely between 50 and 100kHz, from that point the wave distortion starts to be noticed and obviously becomes worse the higher it gets, but there is nothing I can do about it, that's the hardware.

So anyways, thanks for remind me about this, this pic shows pin 15 going nicely at 50Hz, have a go and let me know if anything odd.

![pwm1_50Hz](https://github.com/Rubberazer/JETGPIO/assets/47650457/4f28214e-1621-49b7-a7ac-6d2dd7356cab)

**Comment by democat3457** [comment]
Works perfectly! I updated the error print in #25 to reflect the new minimum Hz.

**Comment by Rubberazer** [comment]
Closing then
